### ISSUE TITLE
LaTeX Size

### ISSUE THREAD

**Issue by peterdsharpe** [kinoute/typora-hivacruz-theme#1]
Hey there,

Thanks for publishing this! I noticed when I was putting this theme through its paces that the LaTeX size seems to be exceptionally small.

![image](https://user-images.githubusercontent.com/6295985/85186725-460bbb80-b260-11ea-8a95-ae29b54d17d9.png)

Not sure if this is on purpose, but I wanted to at least raise the issue!

I'm testing on Windows 10 (v1903 I think), latest version of Typora (v0.9.89). Not sure how exactly Typora does its TeX backend, but if it matters, my default TeX compiler is `lualatex` on this machine.

**Comment by kinoute** [comment]
Hi,

Thanks for this! does the `E = mc2` inline equation have the correct size on your screenshot? The `f(x) = mx + b` equation seems a little small indeed. I'm working on it!

**Comment by kinoute** [comment]
Here are my tests:

Before
![Capture d’écran 2020-06-20 à 08 15 41](https://user-images.githubusercontent.com/623763/85195005-560eb400-b2cf-11ea-9dae-590eb7b1bbf8.png)

A little bigger
![Capture d’écran 2020-06-20 à 08 21 05](https://user-images.githubusercontent.com/623763/85195009-5ad36800-b2cf-11ea-8479-a0d09ff944f2.png)

Bigger
![Capture d’écran 2020-06-20 à 08 22 47](https://user-images.githubusercontent.com/623763/85195017-6161df80-b2cf-11ea-8060-89ee9ae258c6.png)

What do you think?

**Comment by kinoute** [comment]
I released a few new versions with enhancements and fixes to Math Blocks / Inline LateX: 

https://github.com/kinoute/typora-hivacruz-theme/releases

(you can clone the master branch as well)

Please tell me if it works for you!

**Comment by kinoute** [comment]
I'm closing this issue as I increased the LateX size over the recent new versions. Let me know if it doesn't fit your needs
