### ISSUE TITLE
Perference page Bug

### ISSUE THREAD

**Issue by oycol** [kinoute/typora-hivacruz-theme#7]
search bar doesn't fit，and if you switch  the window style  in appearence to unibody，file content will show in the background
![image](https://user-images.githubusercontent.com/23732968/99136668-4e2a2480-2661-11eb-9899-fcfe611177b6.png)
![image](https://user-images.githubusercontent.com/23732968/99136824-44ed8780-2662-11eb-8671-0933a8816c66.png)

**Comment by kinoute** [comment]
Thanks for the report! I will try to look into it ASAP.

**Comment by kinoute** [comment]
@oycol Could you tell me how you got the second screenshot? I'm unable to find on Typora the window with "open, import" etc.

**Comment by oycol** [comment]
Appearence，choose unibody， restart ，then click ，you can see
![image](https://user-images.githubusercontent.com/23732968/99187121-ab23f880-278f-11eb-8080-aefe971d6b89.png)
![image](https://user-images.githubusercontent.com/23732968/99187194-17066100-2790-11eb-8949-804035ef2be7.png)

**Comment by oycol** [comment]
i think dockerfile style is not the best，maybe comment no color or dark color, the instruction has a different color.
![image](https://user-images.githubusercontent.com/23732968/99187645-dcea8e80-2792-11eb-80ed-b4d6d0fdeb6d.png)

**Comment by kinoute** [comment]
OK thanks, I was able to reproduce the issue. I'm working on it!

**Comment by kinoute** [comment]
Fixed the preferences page opacity bug here: https://github.com/kinoute/typora-hivacruz-theme/releases/tag/v0.7

I will try to enhance the search input another time. Regarding the docker file format, I don't have this style while using the source code mode or not:

![Capture d’écran 2020-11-15 à 20 37 50](https://user-images.githubusercontent.com/623763/99194854-85dcbd80-2782-11eb-958f-32d320dfc0ab.png)

Source code mode:

![Capture d’écran 2020-11-15 à 20 38 02](https://user-images.githubusercontent.com/623763/99194862-8ecd8f00-2782-11eb-9c20-58541d5edeeb.png)
