### ISSUE TITLE
Table+line break+highlight causes overlapping

### ISSUE THREAD

**Issue by silencial** [kinoute/typora-hivacruz-theme#8]
As can be seen in the image, if I use highlight inside the table and with multiple lines, there is an overlapping problem.
![image](https://user-images.githubusercontent.com/26143109/99565129-4e942980-2999-11eb-8595-0331fbbdd552.png)

BTW I notice the highlight style inside the table is different from the outside, is it intentional?

**Comment by kinoute** [comment]
Hello,

Thanks for your report! I will try to fix it ASAP. For your second question, It isn't!

**Comment by kinoute** [comment]
@silencial Could you give me a markdown file to reproduce the issue? (the same thing that appears on your screenshot would  be nice)

**Comment by silencial** [comment]
Here it is:
[example.zip](https://github.com/kinoute/typora-hivacruz-theme/files/5719912/example.zip)

I also notice that after turning on numbering math equations in `Preferences->Markdown->Auto Numbering Math Equations`, the math equation is longer displayed in the center as shown in this gif.
![math](https://user-images.githubusercontent.com/26143109/102695829-d5862d00-41f7-11eb-8c4a-c081efb3aa80.gif)

**Comment by kinoute** [comment]
Thanks!

Does it look OK for you?

![Capture d’écran 2020-12-19 à 19 54 59](https://user-images.githubusercontent.com/623763/102697173-2287f480-4234-11eb-94ca-d0d12204b813.png)

**Comment by silencial** [comment]
Looks perfect! 👍

**Comment by kinoute** [comment]
@silencial I just pushed a fix to master, can you confirm it's working for you?

**Comment by silencial** [comment]
Tried it. It is working. Thank you!

**Comment by kinoute** [comment]
Awesome, thanks for the report and for giving me a way to reproduce the bugs. I just released a new version, closing the issue, cheers!
