### ISSUE TITLE
The grave ` key is not rendered properly

### ISSUE THREAD

**Issue by silencial** [kinoute/typora-hivacruz-theme#9]
Everything with the grave key \` does not behave properly.
1. Type \` at the beginning of a line shows nothing until another character is typed
2. Type \` not at the beginning (with some text before it) will show a weird symbol until another character is typed

![grave](https://user-images.githubusercontent.com/26143109/103186068-11229600-488d-11eb-9c13-2c95e9ec96fe.gif)

**Comment by kinoute** [comment]
I'm unable to reproduce what you get:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/623763/103216954-99e61400-4917-11eb-9a28-b2e850d189c0.gif)

This seems similar to what I get with official themes such as the Github one:

![ezgif com-video-to-gif-2](https://user-images.githubusercontent.com/623763/103217000-c9951c00-4917-11eb-819a-0f4856cb52a6.gif)

**Comment by silencial** [comment]
Weird. The default Github theme behaved normally for me.
Can I see your Typora preferences settings?

**Comment by kinoute** [comment]
![Capture d’écran 2020-12-28 à 15 58 43](https://user-images.githubusercontent.com/623763/103223016-a1acb500-4925-11eb-95b1-7fce39dc1b9e.png)
![Capture d’écran 2020-12-28 à 15 58 47](https://user-images.githubusercontent.com/623763/103223012-9fe2f180-4925-11eb-825e-6bed62da6f97.png)

![Capture d’écran 2020-12-28 à 15 58 41](https://user-images.githubusercontent.com/623763/103223019-a2dde200-4925-11eb-96e1-c27f94e86b42.png)
![Capture d’écran 2020-12-28 à 15 58 30](https://user-images.githubusercontent.com/623763/103223023-a5403c00-4925-11eb-94ab-48f7178b749c.png)

**Comment by silencial** [comment]
Changed all to your settings, did not work.

But I found switching to another font in the css setting solved this problem.

**Comment by kinoute** [comment]
Hm, interesting! What is your OS/Typora version?

I like this kind of sneaky bugs. I might look at the Typora/issues repo to see if someone has encountered the same problem.

**Comment by silencial** [comment]
OS: macOS 11.1
Typora: 0.9.9.36.2

**Comment by kinoute** [comment]
Did you encounter the problem on 10.x before upgrading or you weren't using the theme at that time? I need to install Big Sur one day. Might be related to the OS. I'm using Mojave and the same Typora version.

**Comment by silencial** [comment]
Didn't remember now 😂  But highly possible.

**Comment by y761350477** [comment]
This theme also has issues with GitHub Night Theme:  
https://github.com/kinoute/typora-github-night-theme/issues/2

**Comment by kinoute** [comment]
@y761350477 @silencial I just pushed the same fix on this theme, it should be OK now!
